  name: feat_login_screen
  description: "A new Flutter project."
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: '>=3.4.0 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.6
    flutter_svg: ^2.0.10+1

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^3.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/images/logo.svg
      - assets/images/icon_facebook.svg
      - assets/images/icon_headphone.svg
      - assets/images/icon_search.svg
      - assets/images/icon_close.svg
      

    # fonts:
      # - family: NunitoSans
        # fonts:
          # - asset: assets/fonts/NunitoSans-SemiBold.ttf